// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvjJHKYR8wrtyHbXdX4bzKyr49qSmDjB4',
    appId: '1:83222226135:web:1c9a6de4e31c90af543c92',
    messagingSenderId: '83222226135',
    projectId: 'pasji-cuvaj',
    authDomain: 'pasji-cuvaj.firebaseapp.com',
    storageBucket: 'pasji-cuvaj.appspot.com',
    measurementId: 'G-FH3T489R04',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCd8RQN4P4flV-t9EfsLZoN1aa6e-6edNM',
    appId: '1:83222226135:android:df699865d63f9cf0543c92',
    messagingSenderId: '83222226135',
    projectId: 'pasji-cuvaj',
    storageBucket: 'pasji-cuvaj.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXECpVwRo7k68TtpHxViRE0-sjmY7uUZI',
    appId: '1:83222226135:ios:1204bc488a007202543c92',
    messagingSenderId: '83222226135',
    projectId: 'pasji-cuvaj',
    storageBucket: 'pasji-cuvaj.appspot.com',
    iosBundleId: 'com.example.pasjiCuvaj',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXECpVwRo7k68TtpHxViRE0-sjmY7uUZI',
    appId: '1:83222226135:ios:4299cc35578f9e62543c92',
    messagingSenderId: '83222226135',
    projectId: 'pasji-cuvaj',
    storageBucket: 'pasji-cuvaj.appspot.com',
    iosBundleId: 'com.example.pasjiCuvaj.RunnerTests',
  );
}
